# Generated by Django 5.0.1 on 2024-01-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_get', models.CharField(max_length=255, verbose_name='Получатель')),
                ('sender', models.CharField(max_length=255, verbose_name='Отправитель')),
                ('coin_amount', models.SmallIntegerField(verbose_name='Кол-во Coin')),
                ('month', models.CharField(max_length=255, verbose_name='Месяц обучения')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
            },
        ),
    ]
