# Generated by Django 5.0.1 on 2024-01-18 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0004_alter_coin_to_username'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='coins.coin', verbose_name='От пользователя'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='coins.coin', verbose_name='К пользователя'),
        ),
    ]
