# Generated by Django 5.0.1 on 2024-01-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='homework',
            field=models.SmallIntegerField(default=1, verbose_name='За какой дз'),
            preserve_default=False,
        ),
    ]
