# Generated by Django 5.0.1 on 2024-01-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя Студента')),
                ('direction', models.CharField(max_length=255, verbose_name='Напрвление')),
                ('month', models.CharField(max_length=255, verbose_name='Месяц обучения')),
                ('geek_coins', models.CharField(max_length=255, verbose_name='Geek Coin ')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
            },
        ),
    ]
