# Generated by Django 5.0.1 on 2024-01-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='geek_coins',
            field=models.CharField(max_length=255, verbose_name='Кол-во Coin '),
        ),
    ]
