# Generated by Django 5.0.1 on 2024-01-18 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_alter_coin_from_username_alter_coin_to_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='from_username',
            field=models.CharField(max_length=255, verbose_name='Отправитель'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='to_username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_coin', to=settings.AUTH_USER_MODEL, verbose_name='Получатель'),
        ),
    ]
