# Generated by Django 5.0.1 on 2024-01-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0003_alter_coin_from_username_alter_coin_to_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='to_username',
            field=models.CharField(max_length=255, verbose_name='Получатель'),
        ),
    ]
