# Generated by Django 5.0.1 on 2024-01-18 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0004_alter_coin_to_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='from_username',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='to_username',
        ),
        migrations.AddField(
            model_name='coin',
            name='from_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='from_user1', to=settings.AUTH_USER_MODEL, verbose_name='От пользователя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coin',
            name='to_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='to_user1', to=settings.AUTH_USER_MODEL, verbose_name='К пользователя'),
            preserve_default=False,
        ),
    ]
