# Generated by Django 5.0.1 on 2024-01-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0005_remove_coin_from_username_remove_coin_to_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='to_user',
        ),
        migrations.AddField(
            model_name='coin',
            name='from_username',
            field=models.CharField(default=1, max_length=255, verbose_name='Отправитель'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coin',
            name='to_username',
            field=models.CharField(default=1, max_length=255, verbose_name='Получатель'),
            preserve_default=False,
        ),
    ]
